/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b4efaa6d0954076114b4118026d61689)
interface __BaseEnv_Env {
	REPORT_BUNDLES: R2Bucket;
	REPORT_DB: D1Database;
	REPORT_SUBMIT_LIMIT: RateLimit;
	REPORT_READ_LIMIT: RateLimit;
	REPORT_MUTATION_LIMIT: RateLimit;
	REPORT_RECEIPT_LIMIT: RateLimit;
	REPORT_AUTH_FAILURE_LIMIT: RateLimit;
	REPORT_USAGE_LIMIT: RateLimit;
	ENVIRONMENT: "production";
	RELAY_REGISTRY: DurableObjectNamespace<import("./src/index").RelayRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RelayRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
