/**
 * `@vibestudio/rpc` — stateless point-to-point RPC with fetch-shaped
 * streaming. Stateful workspace services can layer their own protocols
 * on top of the same runtime service-resolution path.
 */

export type {
  RpcRequest,
  RpcResponse,
  RpcEvent,
  RpcStreamRequest,
  RpcStreamFrameMessage,
  RpcStreamCancel,
  RpcRequestCancel,
  RpcMessage,
  RpcTransport,
  RpcCallOptions,
  RpcCausalParent,
  RpcStreamOptions,
  AuthenticatedCaller,
  ExposedMethods,
  RpcEventListener,
  RpcCaller,
  CallerKind,
  RpcEnvelope,
  EnvelopeRpcTransport,
  RpcClient,
  RpcClientConfig,
  RpcRequestContext,
  RpcEventContext,
  RpcContextHandler,
  RpcContextMethods,
  RpcContextStreamingHandler,
  RpcPeer,
  RpcContract,
  MethodMap,
  EventMap,
  TypedCallProxy,
  RpcConnectionStatus,
  StreamingMethodHandler,
  StreamingMethodFrame,
  ParentPortEnvelope,
  RpcErrorKind,
  RpcErrorData,
} from "./types.js";
export { RemoteRpcError, RpcBoundaryError, rpcErrorDataOf, rpcErrorKindOf } from "./errors.js";
export type {
  AuthorizationContext,
  AuthorizationOrigin,
  AuthorizationDecision,
  InvocationSnapshot,
  AcquisitionInfo,
  AuthorityFailureInfo,
  AuthorityFailureReasonCode,
  AuthorityPreflightLeaf,
  AuthorityPreflightResult,
  AuthorityRemediationKind,
  AuthorityGrant,
  AuthorityGrantSubject,
  AgentGrantPrincipal,
  AuthorityLock,
  AuthorityGrantConstraints,
  AuthorityRequirement,
  CapabilityScope,
  CodeLineageFact,
  ContextIntegrityFact,
  EntityPrincipal,
  LiveWorkspaceRelationship,
  Principal,
  PrincipalKind,
  ResourceScope,
  SessionMissionFact,
  AgentExecutionMode,
  AgentExecutionTestAuthorityRule,
  AgentExecutionTestCasePolicy,
  AgentExecutionTestPolicy,
  AgentExecutionTestPolicySpec,
  AgentExecutionTestUserlandRule,
  AgentExecutionSessionFact,
} from "./authority.js";
export { isParentPortEnvelope } from "./types.js";
export { createRpcClient, defineContract, withCausalParent } from "./client.js";
export { bytesToBase64, base64ToBytes } from "./base64.js";
export {
  TERMINAL_CLOSE_CODES,
  isTerminalCloseCode,
  CLOSE_TOKEN_REVOKED,
  CLOSE_EXPECTED_AUTH,
  CLOSE_INVALID_TOKEN,
  CLOSE_LEASE_DENIED,
  CLOSE_LEASE_REVOKED,
  CLOSE_PANEL_RETIRED,
} from "./protocol/closeCodes.js";
export {
  createConnectionlessRpcClient,
  collectExposableMethods,
  rpc,
  rpcExposedMethodNames,
  rpcMethodAuthority,
  type RpcAuthorityPolicy,
  type RpcAuthorityEffect,
  type ResolvedRpcAuthority,
  type ConnectionlessRpcClient,
  type ConnectionlessRpcConfig,
} from "./connectionless.js";
export { httpClientTransport, type HttpClientTransportConfig } from "./transports/httpClient.js";
export {
  authenticatedCaller,
  envelopeFromMessage,
  originOfEnvelope,
  responseEnvelopeFor,
  retargetEnvelope,
  stampEnvelopeCaller,
} from "./envelope.js";
export { createHandlerRegistry } from "./transport-helpers.js";
export type { DecodedFramedStream } from "./types.js";
export {
  BRIDGE_STREAM_CHUNK_BYTES,
  BRIDGE_STREAM_BUFFER_CAP_BYTES,
  bridgeStreamSurfaceOf,
  createBridgeBodyReassembler,
  createBridgeStreamRelay,
  decodeBridgeChunk,
  openBridgeStream,
  openBridgeUploadStream,
  type BridgeBodyChunk,
  type BridgeBodyReassembler,
  type BridgeChunkEncoding,
  type BridgeChunkPayload,
  type BridgeStreamMessage,
  type BridgeStreamOpen,
  type BridgeStreamRelay,
  type BridgeStreamRelayDeps,
  type BridgeStreamShellSurface,
} from "./bridgeStream.js";
