export type {
  BrowserName,
  BrowserFamily,
  ImportedBookmark,
  ImportedHistoryEntry,
  ImportedHistoryVisit,
  ImportHistoryBatchMeta,
  ImportBatchMeta,
  ImportedCookie,
  ImportedPassword,
  ImportedAutofillEntry,
  ImportedSearchEngine,
  ImportedFavicon,
  ImportedOpenTab,
  OpenTabsAsPanelsRequest,
  OpenTabsAsPanelsResult,
  OpenTabsPanelDestination,
  OpenTabsPanelGrouping,
  HistoryQuery,
  RecordHistoryVisitRequest,
  UpdateHistoryTitleRequest,
  HistoryAutocompleteQuery,
  BookmarkExportFormat,
  PasswordExportFormat,
  CookieExportFormat,
  HistoryTransition,
  HistoryVisitSource,
  SameSiteValue,
  SourceScheme,
} from "./types.js";

export {
  BrowserNameSchema,
  BrowserFamilySchema,
  HistoryQuerySchema,
  RecordHistoryVisitSchema,
  UpdateHistoryTitleSchema,
  HistoryAutocompleteQuerySchema,
  BookmarkSchema,
  PasswordSchema,
  BROWSER_NAMES,
  BROWSER_FAMILIES,
  HISTORY_VISIT_SOURCES,
} from "./types.js";

export { BrowserDataError } from "./errors.js";
export type { BrowserDataErrorCode } from "./errors.js";

export { createBrowserDataClient } from "./client/browserDataClient.js";
export type {
  BrowserDataClient,
  BrowserPrivacySection,
  ImportPreview,
  NonSensitiveBrowserImportDataType,
  NonSensitiveBrowserImportSelection,
  SensitiveBrowserImportDataType,
  SensitiveBrowserImportCount,
  SensitiveBrowserImportRequest,
  SensitiveBrowserImportPreview,
  SensitiveBrowserImportSelection,
  SensitiveBrowserImportStatus,
} from "./client/browserDataClient.js";
export {
  BROWSER_PRODUCT_SCHEMA,
  BROWSER_VAULT_SCHEMA,
  PAGE_FAVICONS_TABLE_SQL,
} from "./storage/index.js";
export {
  FAVICON_MIME_TYPES,
  MAX_PAGE_FAVICON_BYTES,
  detectFaviconMimeType,
  isFaviconMimeType,
} from "./favicon.js";
export type { FaviconMimeType } from "./favicon.js";
export {
  ApplyCookieMutationsRequestSchema,
  BROWSER_IMPORT_DATA_TYPES,
  BROWSER_PERMISSION_CAPABILITIES,
  BrowserCookieInputSchema,
  BrowserCookieKeySchema,
  BrowserCookiePartitionKeySchema,
  BrowserCookieMutationSchema,
  BrowserEnvironmentIdentitySchema,
  BrowserImportDataTypeSchema,
  BrowserImportSelectionSchema,
  BrowserImportSourceSchema,
  BrowserPermissionCapabilitySchema,
  FORM_FILL_TYPES,
  FormFillSuggestionQuerySchema,
  FormFillTypeSchema,
  IMPORT_HOST_PLATFORMS,
  IMPORT_JOB_PHASES,
  IMPORT_SOURCE_STATUSES,
  ImportCategoryProgressSchema,
  ImportHostSummarySchema,
  ImportJobSnapshotSchema,
  NON_PERSISTABLE_FORM_FILL_TYPES,
  PageFaviconSchema,
  isPersistableFormFillType,
} from "./environment.js";
export {
  BrowserImportCoordinator,
  type BrowserImportHostRegistration,
  type BrowserImportStore,
} from "./importCoordinator.js";
export { RemoteBrowserImportProvider } from "./remoteImportProvider.js";
export {
  browserCookiePartitionFromStorageKey,
  browserCookiePartitionStorageKey,
  normalizeBrowserCookiePartitionKey,
  normalizeCookieExpirationSeconds,
} from "./cookies.js";
export type { BrowserCookiePartitionKey } from "./cookies.js";
export type {
  ApplyCookieMutationsRequest,
  BrowserCookieInput,
  BrowserCookieKey,
  BrowserCookieMutation,
  BrowserCookieRecord,
  BrowserEnvironmentIdentity,
  BrowserImportDataType,
  BrowserDownloadRecord,
  BrowserDownloadState,
  BrowserImportProvider,
  BrowserImportSelection,
  BrowserImportSource,
  BrowserPermissionCapability,
  CookieSnapshot,
  FaviconHandle,
  FormFillSuggestionQuery,
  FormFillType,
  FormFillValueInput,
  ImportBatch,
  ImportBatchSink,
  ImportCategoryBreakdown,
  ImportCategoryBreakdownGroup,
  ImportCategoryProgress,
  ImportedBrowserOpenTab,
  ImportHostPlatform,
  ImportHostSummary,
  ImportJobPhase,
  ImportJobSnapshot,
  ImportPreviewSink,
  ImportPreviewSummary,
  ImportSourceStatus,
  ImportSummary,
  PageFavicon,
  StoredFormFillValue,
} from "./environment.js";
export type {
  StoredBookmark,
  StoredHistory,
  StoredVisit,
  StoredPassword,
  StoredPasswordSummary,
  StoredCookie,
  StoredFormFill,
  StoredSearchEngine,
  StoredPageFavicon,
  StoredImportJob,
  ImportJobWrite,
} from "./storage/index.js";
