import fs from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";
import type { ServiceMethodSchemas } from "../packages/shared/src/typedServiceClient.js";
import { PRODUCT_BUILTINS } from "../packages/service-schemas/src/productBuiltinServices.js";

const root = process.cwd();
const check = process.argv.includes("--check");
const prettier = (await resolveConfig(path.join(root, "package.json"))) ?? {};

const projectMethods = (owner: string, methods: ServiceMethodSchemas) =>
  Object.fromEntries(
    Object.entries(methods).map(([name, method]) => {
      if (
        !method.capability ||
        !method.tier ||
        !method.access?.sensitivity ||
        !method.authority ||
        !("principals" in method.authority)
      ) {
        throw new Error(`Builtin method ${owner}.${name} is incomplete`);
      }
      return [
        name,
        {
          capability: method.capability,
          tier: method.tier.tier,
          session: method.tier.session,
          sensitivity: method.access.sensitivity,
          principals: method.authority.principals,
          presentation: method.presentation ?? null,
          ...(method.execution ? { execution: method.execution } : {}),
          ...("prepared" in method.authority && method.authority.prepared
            ? { prepared: method.authority.prepared }
            : {}),
          effect: method.directEffect ?? {
            kind: "host-capability",
            capability: method.capability,
            resource: { kind: "receiver-object" },
          },
        },
      ];
    })
  );

const entries = PRODUCT_BUILTINS.map((entry) => {
  const methods = entry.kind === "service" ? projectMethods(entry.name, entry.methods) : undefined;
  const directMethodNames = Object.keys(entry.directMethods).sort();
  const source = fs.readFileSync(path.join(root, entry.sourceFile), "utf8");
  if (/@rpc\s*\(/u.test(source)) {
    throw new Error(`${entry.sourceFile} still contains decorator-owned RPC authority`);
  }
  const implementedMethodNames = [
    ...source.matchAll(/@schemaRpc\(\)\s+(?:async\s+)?([A-Za-z_$][A-Za-z0-9_$]*)\s*\(/gu),
  ]
    .map((match) => match[1]!)
    .sort();
  if (implementedMethodNames.join("\n") !== directMethodNames.join("\n")) {
    const implemented = new Set(implementedMethodNames);
    const declared = new Set(directMethodNames);
    throw new Error(
      `${entry.className} direct method schema mismatch: ` +
        `missing=[${implementedMethodNames.filter((name) => !declared.has(name)).join(",")}], ` +
        `unimplemented=[${directMethodNames.filter((name) => !implemented.has(name)).join(",")}]`
    );
  }
  const directMethods = projectMethods(entry.className, entry.directMethods);
  return {
    kind: entry.kind,
    name: entry.name,
    source: entry.source,
    className: entry.className,
    implementation: entry.implementation,
    sourceFile: entry.sourceFile,
    builtinBecause: entry.builtinBecause,
    ...(entry.kind === "service"
      ? {
          title: entry.title,
          description: entry.description,
          action: entry.action,
          presentation: entry.presentation,
          principals: entry.principals,
          protocols: entry.protocols,
          methods,
        }
      : {}),
    durableObject: entry.durableObject,
    workerd: entry.workerd,
    hostCapabilityRequests: entry.hostCapabilityRequests,
    directMethods,
  };
});

const classes = entries.map((entry) => entry.className);
const generatedTs = await format(
  `/* Generated by scripts/generate-builtin-catalog.ts. Do not edit. */\n` +
    `import type { CapabilityPresentation } from "./authorityPresentation.js";\n` +
    `export const PRODUCT_BUILTIN_CATALOG = ${JSON.stringify(entries, null, 2)} as const;\n` +
    `export const INTERNAL_DO_CLASSES = ${JSON.stringify(classes)} as const;\n` +
    `export type InternalDOClassName = (typeof INTERNAL_DO_CLASSES)[number];\n` +
    `export function productBuiltinByIdentity(source: string, className: string) {\n` +
    `  return PRODUCT_BUILTIN_CATALOG.find((entry) => entry.source === source && entry.className === className) ?? null;\n` +
    `}\n` +
    `export function findProductBuiltinService(query: string) {\n` +
    `  for (const entry of PRODUCT_BUILTIN_CATALOG) {\n` +
    `    if (entry.kind === "service" && (entry.name === query || (entry.protocols as readonly string[]).includes(query))) return entry;\n` +
    `  }\n` +
    `  return null;\n` +
    `}\n` +
    `export function productBuiltinMethodCapability(source: string, className: string, method: string): string | null {\n` +
    `  const policy = productBuiltinMethodPolicy(source, className, method);\n` +
    `  return policy?.capability ?? null;\n` +
    `}\n` +
    `export function productBuiltinMethodPolicy(source: string, className: string, method: string) {\n` +
    `  const entry = productBuiltinByIdentity(source, className);\n` +
    `  if (!entry) return null;\n` +
    `  const methods = ("directMethods" in entry ? entry.directMethods : undefined) as unknown as Record<string, { capability: string; tier: "open" | "gated" | "critical"; session: "family" | "codeOnly"; sensitivity: "read" | "write" | "admin" | "destructive"; principals: readonly ("host" | "user" | "code" | "session" | "mission")[]; presentation: CapabilityPresentation | null; execution?: { harness: "attested-system-test" }; prepared?: { resolver: string; contextBoundary?: { operation: "openPanel" | "replacePanel" | "reload" | "unload" | "close" | "movePanel" | "takeOver" | "rebuildPanel" | "updatePanelState"; targetArgument: number; targetPath?: readonly (string | number)[]; requestedContextPath?: readonly (string | number)[]; requestedContextLookup?: { method: string; arguments: readonly { argument: number; path?: readonly (string | number)[] }[]; resultPath: readonly (string | number)[] } }; leaves: readonly { capability?: string; capabilityPrefix?: string; requirement: import("./authorization.js").AuthorityRequirement | { kind: "selected"; principals: readonly ("host" | "user" | "code" | "session" | "mission")[] }; tier?: "open" | "gated" | "critical" | { selectedFrom: readonly ("gated" | "critical")[] } }[] }; effect: { kind: string } }> | undefined;\n` +
    `  if (!methods) return null;\n` +
    `  return Object.prototype.hasOwnProperty.call(methods, method) ? methods[method]! : null;\n` +
    `}\n` +
    `export function productBuiltinCapabilityPresentation(capability: string): CapabilityPresentation | null {\n` +
    `  for (const entry of PRODUCT_BUILTIN_CATALOG) {\n` +
    `    for (const method of Object.values(entry.directMethods)) {\n` +
    `      if (method.capability === capability && method.presentation) return method.presentation;\n` +
    `    }\n` +
    `  }\n` +
    `  return null;\n` +
    `}\n` +
    `export function productBuiltinCapabilityCategory(capability: string): NonNullable<CapabilityPresentation["authorityCategory"]> | null {\n` +
    `  return productBuiltinCapabilityPresentation(capability)?.authorityCategory ?? null;\n` +
    `}\n` +
    `export function productBuiltinMethodRequests(source: string, className: string, method: string) {\n` +
    `  const entry = productBuiltinByIdentity(source, className);\n` +
    `  if (!entry) return [];\n` +
    `  return entry.hostCapabilityRequests\n` +
    `    .filter((request) => (request.methods as readonly string[]).includes(method))\n` +
    `    .map(({ methods: _methods, tier: _tier, evidence: _evidence, ...scope }) => scope);\n` +
    `}\n`,
  { ...prettier, parser: "typescript" }
);
const generatedMjs =
  `/* Generated by scripts/generate-builtin-catalog.ts. Do not edit. */\n` +
  `export const PRODUCT_BUILTIN_CATALOG = Object.freeze(${JSON.stringify(entries, null, 2)});\n` +
  `export function productBuiltinByIdentity(source, className) {\n` +
  `  return PRODUCT_BUILTIN_CATALOG.find((entry) => entry.source === source && entry.className === className) ?? null;\n` +
  `}\n` +
  `export function productBuiltinMethodCapability(source, className, method) {\n` +
  `  const policy = productBuiltinMethodPolicy(source, className, method);\n` +
  `  return policy?.capability ?? null;\n` +
  `}\n` +
  `export function productBuiltinMethodPolicy(source, className, method) {\n` +
  `  const entry = productBuiltinByIdentity(source, className);\n` +
  `  if (!entry || !entry.directMethods) return null;\n` +
  `  return Object.prototype.hasOwnProperty.call(entry.directMethods, method) ? entry.directMethods[method] : null;\n` +
  `}\n` +
  `export function productBuiltinCapabilityPresentation(capability) {\n` +
  `  for (const entry of PRODUCT_BUILTIN_CATALOG) {\n` +
  `    for (const method of Object.values(entry.directMethods)) {\n` +
  `      if (method.capability === capability && method.presentation) return method.presentation;\n` +
  `    }\n` +
  `  }\n` +
  `  return null;\n` +
  `}\n` +
  `export function productBuiltinMethodRequests(source, className, method) {\n` +
  `  const entry = productBuiltinByIdentity(source, className);\n` +
  `  if (!entry) return [];\n` +
  `  return entry.hostCapabilityRequests\n` +
  `    .filter((request) => request.methods.includes(method))\n` +
  `    .map(({ methods: _methods, tier: _tier, evidence: _evidence, ...scope }) => scope);\n` +
  `}\n`;
const generatedIndex = await format(
  `/* Generated by scripts/generate-builtin-catalog.ts. Do not edit. */\n${entries
    .map((entry) => `export { ${entry.className} } from "${entry.implementation}";`)
    .join("\n")}\n`,
  { ...prettier, parser: "typescript" }
);

const executionCatalog = {
  version: 2,
  classes: Object.fromEntries(
    entries.map((entry) => [
      entry.className,
      {
        provides: [],
        requests: [],
        methodScopedRequests: entry.hostCapabilityRequests,
      },
    ])
  ),
};
const generatedExecutionCatalog = await format(JSON.stringify(executionCatalog), {
  ...prettier,
  parser: "json",
});

const outputs = new Map<string, string>([
  ["packages/shared/src/productBuiltinCatalog.generated.ts", generatedTs],
  ["packages/shared/src/productBuiltinCatalog.node.generated.mjs", generatedMjs],
  ["src/server/internalDOs/index.ts", generatedIndex],
  [
    "src/server/internalDOs/internalDoExecutionCatalog.json",
    generatedExecutionCatalog,
  ],
]);
for (const [relative, content] of outputs) {
  const target = path.join(root, relative);
  if (check) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content) {
      throw new Error(`${relative} is stale; run pnpm generate:builtin-catalog`);
    }
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
  }
}
