#!/bin/sh
# Let a source checkout's workspace runtimes create the user namespace
# bubblewrap needs.
#
# Ubuntu 24.04+ sets kernel.apparmor_restrict_unprivileged_userns=1 and denies
# unprivileged user namespaces to any binary shipping no AppArmor profile, so a
# workspace fails with "bwrap: setting up uid map: Permission denied". Packaged
# installs (deb/rpm/pacman) get build-resources/apparmor/vibestudio-mxc from
# their maintainer scripts, but a profile attaches by absolute path and a
# checkout's launcher lives wherever the developer cloned it.
#
# This grants that one permission for this checkout's launcher and nothing
# else, keeping bubblewrap confinement exactly as it is in a packaged install
# rather than weakening the machine's policy or running workspaces unconfined.
set -e

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
PROFILE_NAME=vibestudio-mxc-dev
PROFILE_TARGET="/etc/apparmor.d/${PROFILE_NAME}"
LAUNCHER_GLOB="${REPO_ROOT}/dist/mxc/*/lxc-exec"

if [ "$(uname -s)" != "Linux" ]; then
  echo "Only Linux hosts restrict unprivileged user namespaces this way; nothing to install." >&2
  exit 0
fi

if [ ! -d /etc/apparmor.d ]; then
  echo "This host has no /etc/apparmor.d, so AppArmor is not what refuses the sandbox." >&2
  exit 0
fi

# The profile names one exact checkout. Refuse to write a profile for a tree
# whose launcher has never been built, rather than silently covering nothing.
if ! ls "${REPO_ROOT}"/dist/mxc/*/lxc-exec >/dev/null 2>&1; then
  echo "No MXC launcher under ${REPO_ROOT}/dist/mxc; run a build first." >&2
  exit 1
fi

if [ "$(id -u)" != "0" ]; then
  echo "Installing an AppArmor profile needs root. Re-run:" >&2
  echo "  sudo $0" >&2
  exit 1
fi

cat > "$PROFILE_TARGET" <<PROFILE
# Generated by scripts/install-dev-apparmor-profile.sh for the checkout at
# ${REPO_ROOT}. Packaged installs use build-resources/apparmor/vibestudio-mxc
# instead; this file covers only this developer tree and can be removed with
#   sudo apparmor_parser --remove ${PROFILE_TARGET} && sudo rm ${PROFILE_TARGET}
abi <abi/4.0>,

include <tunables/global>

profile ${PROFILE_NAME} "${LAUNCHER_GLOB}" flags=(unconfined) {
  userns,

  # bubblewrap creates the namespace on the launcher's behalf, so it has to be
  # covered by the same permission rather than falling back to unconfined.
  /usr/bin/bwrap ix,

  include if exists <local/${PROFILE_NAME}>
}
PROFILE
chmod 0644 "$PROFILE_TARGET"

if ! command -v apparmor_parser >/dev/null 2>&1; then
  echo "Wrote $PROFILE_TARGET, but apparmor_parser is missing; load it once AppArmor is available." >&2
  exit 0
fi

apparmor_parser --replace --skip-cache "$PROFILE_TARGET"
echo "Loaded $PROFILE_NAME for ${LAUNCHER_GLOB}."
echo "Verify with: pnpm system-test --instance apparmor-check doctor"
