import type { CapabilityPresentation } from "../authorityPresentation.js";
import type { HostSemanticCapability } from "./hostMethodCapabilities.js";
import { METHOD_TIERS, type ReviewedHostMethod } from "./tierTable.js";

type PromptableHostMethod = {
  [Method in ReviewedHostMethod]: (typeof METHOD_TIERS)[Method]["tier"] extends "open"
    ? never
    : Method;
}[ReviewedHostMethod];

/**
 * Reviewed user-facing copy for every promptable static host method.
 *
 * This is intentionally a static census: host methods ship with the host. Dynamic
 * workspace services supply their title and description from the live workspace
 * declaration instead. A new gated/critical host method fails type-check until its
 * effect is named here; transport method names are never prompt copy.
 */
export const HOST_CAPABILITY_PRESENTATIONS = {
  "adblock.addCustomList": {
    title: "Add a custom ad-blocking list",
    action: "add a custom ad-blocking list",
    description: "Allows {requesterKind} to add a custom ad-blocking list.",
    group: "network",
  },
  "adblock.rebuildEngine": {
    title: "Refresh ad blocking",
    action: "refresh ad blocking",
    description: "Allows {requesterKind} to refresh ad blocking.",
    group: "network",
  },
  "adblock.removeCustomList": {
    title: "Remove a custom ad-blocking list",
    action: "remove a custom ad-blocking list",
    description: "Allows {requesterKind} to remove a custom ad-blocking list.",
    group: "network",
  },
  "adblock.removeFromWhitelist": {
    title: "Resume blocking ads on a website",
    action: "resume blocking ads on a website",
    description: "Allows {requesterKind} to resume blocking ads on a website.",
    group: "network",
  },
  "adblock.resetStats": {
    title: "Clear ad-blocking statistics",
    action: "clear ad-blocking statistics",
    description: "Allows {requesterKind} to clear ad-blocking statistics.",
    group: "network",
  },
  "adblock.resetStatsForPanel": {
    title: "Clear a panel's ad-blocking statistics",
    action: "clear a panel's ad-blocking statistics",
    description: "Allows {requesterKind} to clear a panel's ad-blocking statistics.",
    group: "network",
  },
  "adblock.setEnabled": {
    title: "Turn ad blocking on or off",
    action: "turn ad blocking on or off",
    description: "Allows {requesterKind} to turn ad blocking on or off.",
    group: "network",
  },
  "adblock.setEnabledForPanel": {
    title: "Change ad blocking for a panel",
    action: "change ad blocking for a panel",
    description: "Allows {requesterKind} to change ad blocking for a panel.",
    group: "network",
  },
  "adblock.setListEnabled": {
    title: "Turn an ad-blocking list on or off",
    action: "turn an ad-blocking list on or off",
    description: "Allows {requesterKind} to turn an ad-blocking list on or off.",
    group: "network",
  },
  "app.applyUpdate": {
    title: "Install an application update",
    action: "install an application update",
    description: "Allows {requesterKind} to install an application update.",
    group: "host",
  },
  "app.clearBuildCache": {
    title: "Clear cached build files",
    action: "clear cached build files",
    description: "Allows {requesterKind} to clear cached build files.",
    group: "host",
  },
  "app.openExternal": {
    title: "Open a link in another application",
    action: "open a link in another application",
    description: "Allows {requesterKind} to open a link in another application.",
    group: "host",
  },
  "audit.query": {
    title: "View the security activity log",
    action: "view the security activity log",
    description: "Allows {requesterKind} to view the security activity log.",
    group: "approvals",
  },
  "autofill.confirmSave": {
    title: "Save this password choice",
    action: "save this password choice",
    description:
      "Allows {requesterKind} to save a password or remember that password saving is disabled for this site.",
    group: "credentials",
  },
  "autofill.deleteSavedPassword": {
    title: "Delete a saved password",
    action: "permanently delete a saved password",
    description: "Allows {requesterKind} to permanently delete one saved browser password.",
    group: "credentials",
  },
  "autofill.listNeverSaveOrigins": {
    title: "View password-saving preferences",
    action: "view sites excluded from password-saving prompts",
    description: "Allows {requesterKind} to view sites where password saving is disabled.",
    group: "credentials",
  },
  "autofill.listSavedPasswords": {
    title: "View saved password accounts",
    action: "view saved account names and websites",
    description:
      "Allows {requesterKind} to view saved account names and websites, but not password contents.",
    group: "credentials",
  },
  "autofill.removeNeverSaveOrigin": {
    title: "Offer to save passwords for a site",
    action: "offer to save passwords for a site again",
    description: "Allows {requesterKind} to re-enable password-saving prompts for one site.",
    group: "credentials",
  },
  "auth.grantConnection": {
    title: "Allow a new client connection",
    action: "allow a new client connection",
    description: "Allows {requesterKind} to allow a new client connection.",
    group: "accounts",
  },
  "auth.mintAgentCredential": {
    title: "Create a sign-in key for an agent",
    action: "create a sign-in key for an agent",
    description: "Allows {requesterKind} to create a sign-in key for an agent.",
    group: "accounts",
  },
  "auth.revokeAgentCredential": {
    title: "Revoke an agent's sign-in key",
    action: "revoke an agent's sign-in key",
    description: "Allows {requesterKind} to revoke an agent's sign-in key.",
    group: "accounts",
  },
  "blobstore.delete": {
    title: "Delete stored workspace data",
    action: "delete stored workspace data",
    description: "Allows {requesterKind} to delete stored workspace data.",
    group: "files",
  },
  "blobstore.materializeTree": {
    title: "Restore a stored folder tree",
    action: "restore a stored folder tree",
    description: "Allows {requesterKind} to restore a stored folder tree.",
    group: "files",
  },
  "build.doctorExtension": {
    title: "Diagnose an extension",
    action: "diagnose an extension",
    description: "Allows {requesterKind} to diagnose an extension.",
    group: "workspace",
  },
  "build.gc": {
    title: "Clean unused build files",
    action: "clean unused build files",
    description: "Allows {requesterKind} to clean unused build files.",
    group: "workspace",
  },
  "build.getBuildNpm": {
    title: "Inspect installed packages for an app, panel, worker, or extension",
    action: "inspect installed packages for an app, panel, worker, or extension",
    description:
      "Allows {requesterKind} to inspect installed packages for an app, panel, worker, or extension.",
    group: "workspace",
  },
  "build.recompute": {
    title: "Rebuild workspace apps, panels, workers, and extensions",
    action: "rebuild workspace apps, panels, workers, and extensions",
    description:
      "Allows {requesterKind} to rebuild workspace apps, panels, workers, and extensions.",
    group: "workspace",
  },
  "contentTrust.addPolicy": {
    title: "Always trust matching outside content",
    action: "always trust matching outside content",
    description: "Allows {requesterKind} to always trust matching outside content.",
    group: "approvals",
  },
  "contentTrust.revoke": {
    title: "Remove a content-trust decision",
    action: "remove a content-trust decision",
    description: "Allows {requesterKind} to remove a content-trust decision.",
    group: "approvals",
  },
  "contentTrust.vouch": {
    title: "Trust this exact outside content",
    action: "trust this exact outside content",
    description: "Allows {requesterKind} to trust this exact outside content.",
    group: "approvals",
  },
  "credentials.audit": {
    title: "View connected-account activity",
    action: "view connected-account activity",
    description: "Allows {requesterKind} to view connected-account activity.",
    group: "credentials",
  },
  "credentials.cancelOAuth": {
    title: "Cancel account sign-in",
    action: "cancel account sign-in",
    description: "Allows {requesterKind} to cancel account sign-in.",
    group: "credentials",
  },
  "credentials.completeCapture": {
    title: "Save submitted account details",
    action: "save submitted account details",
    description: "Allows {requesterKind} to save submitted account details.",
    group: "credentials",
  },
  "credentials.configureClient": {
    title: "Configure an account provider",
    action: "configure an account provider",
    description: "Allows {requesterKind} to configure an account provider.",
    group: "credentials",
  },
  "credentials.connect": {
    title: "Connect an account",
    action: "connect an account",
    description: "Allows {requesterKind} to connect an account.",
    group: "credentials",
  },
  "credentials.deleteClientConfig": {
    title: "Delete account-provider settings",
    action: "delete account-provider settings",
    description: "Allows {requesterKind} to delete account-provider settings.",
    group: "credentials",
  },
  "credentials.forwardOAuthCallback": {
    title: "Complete account sign-in",
    action: "complete account sign-in",
    description: "Allows {requesterKind} to complete account sign-in.",
    group: "credentials",
  },
  "credentials.inspectStoredCredentials": {
    title: "View which connected accounts are stored",
    action: "view which connected accounts are stored",
    description: "Allows {requesterKind} to view which connected accounts are stored.",
    group: "credentials",
  },
  "credentials.proxyFetch": {
    title: "Use a connected account with an external service",
    action: "use a connected account with an external service",
    description: "Allows {requesterKind} to use a connected account with an external service.",
    group: "credentials",
  },
  "credentials.proxyGitHttp": {
    title: "Use a connected account with a Git remote",
    action: "use a connected account with a Git remote",
    description: "Allows {requesterKind} to use a connected account with a Git remote.",
    group: "credentials",
  },
  "credentials.requestCredentialInput": {
    title: "Ask for account details",
    action: "ask for account details",
    description: "Allows {requesterKind} to ask for account details.",
    group: "credentials",
  },
  "credentials.resolveCredential": {
    title: "Use a matching connected account",
    action: "use a matching connected account",
    description: "Allows {requesterKind} to use a matching connected account.",
    group: "credentials",
  },
  "credentials.revokeCredential": {
    title: "Disconnect an account",
    action: "disconnect an account",
    description: "Allows {requesterKind} to disconnect an account.",
    group: "credentials",
  },
  "credentials.storeCredential": {
    title: "Save a connected account",
    action: "save a connected account",
    description: "Allows {requesterKind} to save a connected account.",
    group: "credentials",
  },
  "eval.reset": {
    title: "Reset the code runner",
    action: "reset the code runner",
    description: "Allows {requesterKind} to reset the code runner.",
    group: "runtime",
  },
  "extensions.reload": {
    title: "Reload workspace extensions",
    action: "reload workspace extensions",
    description: "Allows {requesterKind} to reload workspace extensions.",
    group: "workspace",
  },
  "gateway.fetch": {
    title: "Access a workspace gateway address",
    action: "access a workspace gateway address",
    description: "Allows {requesterKind} to access a workspace gateway address.",
    group: "network",
  },
  "gitInterop.completeWorkspaceDependencies": {
    title: "Download missing project dependencies",
    action: "download missing project dependencies",
    description: "Allows {requesterKind} to download missing project dependencies.",
    group: "files",
  },
  "gitInterop.createDisposableRemote": {
    title: "Create a temporary Git remote",
    action: "create a temporary Git remote",
    description: "Allows {requesterKind} to create a temporary Git remote.",
    group: "files",
  },
  "gitInterop.detachUpstream": {
    title: "Disconnect the upstream Git repository",
    action: "disconnect the upstream Git repository",
    description: "Allows {requesterKind} to disconnect the upstream Git repository.",
    group: "files",
  },
  "gitInterop.importProject": {
    title: "Import a Git project",
    action: "import a Git project",
    description: "Allows {requesterKind} to import a Git project.",
    group: "files",
  },
  "gitInterop.publishRepo": {
    title: "Publish a workspace repository",
    action: "publish a workspace repository",
    description: "Allows {requesterKind} to publish a workspace repository.",
    group: "files",
  },
  "gitInterop.publishToDisposableRemote": {
    title: "Publish to a temporary Git remote",
    action: "publish to a temporary Git remote",
    description: "Allows {requesterKind} to publish to a temporary Git remote.",
    group: "files",
  },
  "gitInterop.pullUpstream": {
    title: "Pull changes from the upstream Git repository",
    action: "pull changes from the upstream Git repository",
    description: "Allows {requesterKind} to pull changes from the upstream Git repository.",
    group: "files",
  },
  "gitInterop.pushDisposableRemote": {
    title: "Push changes to a temporary Git remote",
    action: "push changes to a temporary Git remote",
    description: "Allows {requesterKind} to push changes to a temporary Git remote.",
    group: "files",
  },
  "gitInterop.pushUpstream": {
    title: "Push changes to the upstream Git repository",
    action: "push changes to the upstream Git repository",
    description: "Allows {requesterKind} to push changes to the upstream Git repository.",
    group: "files",
  },
  "gitInterop.removeDisposableRemote": {
    title: "Remove a temporary Git remote",
    action: "remove a temporary Git remote",
    description: "Allows {requesterKind} to remove a temporary Git remote.",
    group: "files",
  },
  "gitInterop.removeSharedRemote": {
    title: "Remove the shared Git remote",
    action: "remove the shared Git remote",
    description: "Allows {requesterKind} to remove the shared Git remote.",
    group: "files",
  },
  "gitInterop.removeUpstream": {
    title: "Remove the upstream Git remote",
    action: "remove the upstream Git remote",
    description: "Allows {requesterKind} to remove the upstream Git remote.",
    group: "files",
  },
  "gitInterop.setAutoPush": {
    title: "Change automatic Git pushing",
    action: "change automatic Git pushing",
    description: "Allows {requesterKind} to change automatic Git pushing.",
    group: "files",
  },
  "gitInterop.setSharedRemote": {
    title: "Change the shared Git remote",
    action: "change the shared Git remote",
    description: "Allows {requesterKind} to change the shared Git remote.",
    group: "files",
  },
  "gitInterop.setUpstream": {
    title: "Change the upstream Git repository",
    action: "change the upstream Git repository",
    description: "Allows {requesterKind} to change the upstream Git repository.",
    group: "files",
  },
  "governance.list": {
    title: "View workspace governance settings",
    action: "view workspace governance settings",
    description: "Allows {requesterKind} to view workspace governance settings.",
    group: "approvals",
  },
  "hostLifecycle.shutdown": {
    title: "Shut down the workspace host",
    action: "shut down the workspace host",
    description: "Allows {requesterKind} to shut down the workspace host.",
    group: "host",
  },
  "hubControl.addWorkspaceMember": {
    title: "Add a workspace member",
    action: "add a workspace member",
    description: "Allows {requesterKind} to add a workspace member.",
    group: "accounts",
  },
  "hubControl.createWorkspace": {
    title: "Create a workspace",
    action: "create a workspace",
    description: "Allows {requesterKind} to create a workspace.",
    group: "accounts",
  },
  "hubControl.deleteWorkspace": {
    title: "Delete a workspace",
    action: "delete a workspace",
    description: "Allows {requesterKind} to delete a workspace.",
    group: "accounts",
  },
  "hubControl.ensureEphemeralWorkspace": {
    title: "Prepare a temporary workspace",
    action: "prepare a temporary workspace",
    description: "Allows {requesterKind} to prepare a temporary workspace.",
    group: "accounts",
  },
  "hubControl.getProfile": {
    title: "View an account profile",
    action: "view an account profile",
    description: "Allows {requesterKind} to view an account profile.",
    group: "accounts",
  },
  "hubControl.inviteUser": {
    title: "Invite someone to the workspace",
    action: "invite someone to the workspace",
    description: "Allows {requesterKind} to invite someone to the workspace.",
    group: "accounts",
  },
  "hubControl.listDevices": {
    title: "View connected devices",
    action: "view connected devices",
    description: "Allows {requesterKind} to view connected devices.",
    group: "accounts",
  },
  "hubControl.listUserPresence": {
    title: "View who is currently active",
    action: "view who is currently active",
    description: "Allows {requesterKind} to view who is currently active.",
    group: "accounts",
  },
  "hubControl.listWorkspaceMembers": {
    title: "View workspace members",
    action: "view workspace members",
    description: "Allows {requesterKind} to view workspace members.",
    group: "accounts",
  },
  "hubControl.listWorkspaces": {
    title: "View available workspaces",
    action: "view available workspaces",
    description: "Allows {requesterKind} to view available workspaces.",
    group: "accounts",
  },
  "hubControl.pairDevice": {
    title: "Pair a device",
    action: "pair a device",
    description: "Allows {requesterKind} to pair a device.",
    group: "accounts",
  },
  "hubControl.removeWorkspaceMember": {
    title: "Remove a workspace member",
    action: "remove a workspace member",
    description: "Allows {requesterKind} to remove a workspace member.",
    group: "accounts",
  },
  "hubControl.revokeDevice": {
    title: "Disconnect a device",
    action: "disconnect a device",
    description: "Allows {requesterKind} to disconnect a device.",
    group: "accounts",
  },
  "hubControl.revokeUser": {
    title: "Revoke a user's access",
    action: "revoke a user's access",
    description: "Allows {requesterKind} to revoke a user's access.",
    group: "accounts",
  },
  "hubControl.routeWorkspace": {
    title: "Connect to a workspace",
    action: "connect to a workspace",
    description: "Allows {requesterKind} to connect to a workspace.",
    group: "accounts",
  },
  "hubControl.setRole": {
    title: "Change a workspace member's role",
    action: "change a workspace member's role",
    description: "Allows {requesterKind} to change a workspace member's role.",
    group: "accounts",
  },
  "hubControl.updateProfile": {
    title: "Change an account profile",
    action: "change an account profile",
    description: "Allows {requesterKind} to change an account profile.",
    group: "accounts",
  },
  "mission.approve": {
    title: "Enable an automation",
    action: "enable an automation",
    description: "Allows {requesterKind} to enable an automation.",
    group: "runtime",
  },
  "mission.createDraft": {
    title: "Create an automation draft",
    action: "create an automation draft",
    description: "Allows {requesterKind} to create an automation draft.",
    group: "runtime",
  },
  "mission.edit": {
    title: "Change an automation",
    action: "change an automation",
    description: "Allows {requesterKind} to change an automation.",
    group: "runtime",
  },
  "mission.finishSession": {
    title: "Finish an automation run",
    action: "finish an automation run",
    description: "Allows {requesterKind} to finish an automation run.",
    group: "runtime",
  },
  "mission.pause": {
    title: "Pause an automation",
    action: "pause an automation",
    description: "Allows {requesterKind} to pause an automation.",
    group: "runtime",
  },
  "mission.resume": {
    title: "Resume an automation",
    action: "resume an automation",
    description: "Allows {requesterKind} to resume an automation.",
    group: "runtime",
  },
  "mission.retire": {
    title: "Remove an automation",
    action: "remove an automation",
    description: "Allows {requesterKind} to remove an automation.",
    group: "runtime",
  },
  "mission.startSession": {
    title: "Start an automation run",
    action: "start an automation run",
    description: "Allows {requesterKind} to start an automation run.",
    group: "runtime",
  },
  "panelCdp.getCdpEndpoint": {
    title: "Inspect a panel with developer tools",
    action: "inspect a panel with developer tools",
    description: "Allows {requesterKind} to inspect a panel with developer tools.",
    group: "panels",
  },
  "panelCdp.hostProvider.close": {
    title: "Stop inspecting a panel",
    action: "stop inspecting a panel",
    description: "Allows {requesterKind} to stop inspecting a panel.",
    group: "panels",
  },
  "panelCdp.hostProvider.open": {
    title: "Inspect a panel",
    action: "inspect a panel",
    description: "Allows {requesterKind} to inspect a panel.",
    group: "panels",
  },
  "panelCdp.hostProvider.send": {
    title: "Control an inspected panel",
    action: "control an inspected panel",
    description: "Allows {requesterKind} to control an inspected panel.",
    group: "panels",
  },
  "permissions.list": {
    title: "View saved site permissions",
    action: "view saved site permissions",
    description: "Allows {requesterKind} to view saved site permissions.",
    group: "approvals",
  },
  "permissions.revoke": {
    title: "Remove a saved site permission",
    action: "remove a saved site permission",
    description: "Allows {requesterKind} to remove a saved site permission.",
    group: "approvals",
  },
  "phoneProvisioning.devices": {
    title: "View available mobile devices",
    action: "view available mobile devices",
    description: "Allows {requesterKind} to view available mobile devices.",
    group: "host",
  },
  "phoneProvisioning.install": {
    title: "Install a mobile build",
    action: "install a mobile build",
    description: "Allows {requesterKind} to install a mobile build.",
    group: "host",
  },
  "phoneProvisioning.openPairing": {
    title: "Open mobile-device pairing",
    action: "open mobile-device pairing",
    description: "Allows {requesterKind} to open mobile-device pairing.",
    group: "host",
  },
  "phoneProvisioning.providers": {
    title: "View mobile build providers",
    action: "view mobile build providers",
    description: "Allows {requesterKind} to view mobile build providers.",
    group: "host",
  },
  "presence.getPanelActiveOwner": {
    title: "View who is using a panel",
    action: "view who is using a panel",
    description: "Allows {requesterKind} to view who is using a panel.",
    group: "accounts",
  },
  "presence.markPanelActive": {
    title: "Mark a panel as active",
    action: "mark a panel as active",
    description: "Allows {requesterKind} to mark a panel as active.",
    group: "accounts",
  },
  "presence.markPanelsOwned": {
    title: "Claim ownership of panels",
    action: "claim ownership of panels",
    description: "Allows {requesterKind} to claim ownership of panels.",
    group: "accounts",
  },
  "push.listRegistrations": {
    title: "View devices registered for notifications",
    action: "view devices registered for notifications",
    description: "Allows {requesterKind} to view devices registered for notifications.",
    group: "notifications",
  },
  "push.register": {
    title: "Enable notifications on a device",
    action: "enable notifications on a device",
    description: "Allows {requesterKind} to enable notifications on a device.",
    group: "notifications",
  },
  "push.send": {
    title: "Send a notification",
    action: "send a notification",
    description: "Allows {requesterKind} to send a notification.",
    group: "notifications",
  },
  "push.unregister": {
    title: "Disable notifications on a device",
    action: "disable notifications on a device",
    description: "Allows {requesterKind} to disable notifications on a device.",
    group: "notifications",
  },
  "remoteCred.clear": {
    title: "Clear a remote connection",
    action: "clear a remote connection",
    description: "Allows {requesterKind} to clear a remote connection.",
    group: "credentials",
  },
  "remoteCred.getCurrent": {
    title: "View the current remote connection",
    action: "view the current remote connection",
    description: "Allows {requesterKind} to view the current remote connection.",
    group: "credentials",
  },
  "remoteCred.pair": {
    title: "Pair a remote connection",
    action: "pair a remote connection",
    description: "Allows {requesterKind} to pair a remote connection.",
    group: "credentials",
  },
  "remoteCred.reconnectNow": {
    title: "Reconnect now",
    action: "reconnect now",
    description: "Allows {requesterKind} to reconnect now.",
    group: "credentials",
  },
  "remoteCred.relaunch": {
    title: "Restart the remote connection",
    action: "restart the remote connection",
    description: "Allows {requesterKind} to restart the remote connection.",
    group: "credentials",
  },
  "runtime.cloneContext": {
    title: "Copy another task's workspace",
    action: "copy another task's workspace",
    description: "Allows {requesterKind} to copy another task's workspace.",
    group: "runtime",
  },
  "runtime.createSubagentContext": {
    title: "Create a workspace for a subagent",
    action: "create a workspace for a subagent",
    description: "Allows {requesterKind} to create a workspace for a subagent.",
    group: "runtime",
  },
  "runtime.recordContextEdge": {
    title: "Link related task workspaces",
    action: "link related task workspaces",
    description: "Allows {requesterKind} to link related task workspaces.",
    group: "runtime",
  },
  "serverLog.query": {
    title: "View server logs",
    action: "view server logs",
    description: "Allows {requesterKind} to view server logs.",
    group: "host",
  },
  "serverLog.stats": {
    title: "View server log statistics",
    action: "view server log statistics",
    description: "Allows {requesterKind} to view server log statistics.",
    group: "host",
  },
  "serverLog.tail": {
    title: "Follow new server log entries",
    action: "follow new server log entries",
    description: "Allows {requesterKind} to follow new server log entries.",
    group: "host",
  },
  "settings.getData": {
    title: "View application settings",
    action: "view application settings",
    description: "Allows {requesterKind} to view application settings.",
    group: "host",
  },
  "shellApproval.blockCapability": {
    title: "Block a requested action",
    action: "block a requested action",
    description: "Allows {requesterKind} to block a requested action.",
    group: "approvals",
  },
  "shellApproval.listPending": {
    title: "View requests awaiting your decision",
    action: "view requests awaiting your decision",
    description: "Allows {requesterKind} to view requests awaiting your decision.",
    group: "approvals",
  },
  "shellApproval.resolve": {
    title: "Respond to a workspace request",
    action: "respond to a workspace request",
    description: "Allows {requesterKind} to respond to a workspace request.",
    group: "approvals",
  },
  "shellApproval.resolveBootstrap": {
    title: "Approve initial workspace access",
    action: "approve initial workspace access",
    description: "Allows {requesterKind} to approve initial workspace access.",
    group: "approvals",
  },
  "shellApproval.resolveExternalAgent": {
    title: "Respond to an external agent request",
    action: "respond to an external agent request",
    description: "Allows {requesterKind} to respond to an external agent request.",
    group: "approvals",
  },
  "shellApproval.resolveExternalAgentByRequest": {
    title: "Respond to an external agent request",
    action: "respond to an external agent request",
    description: "Allows {requesterKind} to respond to an external agent request.",
    group: "approvals",
  },
  "shellApproval.resolveUserland": {
    title: "Respond to a workspace service request",
    action: "respond to a workspace service request",
    description: "Allows {requesterKind} to respond to a workspace service request.",
    group: "approvals",
  },
  "shellApproval.submitClientConfig": {
    title: "Submit account-provider settings",
    action: "submit account-provider settings",
    description: "Allows {requesterKind} to submit account-provider settings.",
    group: "approvals",
  },
  "shellApproval.submitCredentialInput": {
    title: "Submit account details",
    action: "submit account details",
    description: "Allows {requesterKind} to submit account details.",
    group: "approvals",
  },
  "shellApproval.submitSecretInput": {
    title: "Submit a protected value",
    action: "submit a protected value",
    description: "Allows {requesterKind} to submit a protected value.",
    group: "approvals",
  },
  "userlandApproval.list": {
    title: "View workspace service requests",
    action: "view workspace service requests",
    description: "Allows {requesterKind} to view workspace service requests.",
    group: "approvals",
  },
  "userlandApproval.request": {
    title: "Ask the user to approve a workspace action",
    action: "ask the user to approve a workspace action",
    description: "Allows {requesterKind} to ask the user to approve a workspace action.",
    group: "approvals",
  },
  "userlandApproval.requestAs": {
    title: "Ask the user to approve a workspace action",
    action: "ask the user to approve a workspace action",
    description: "Allows {requesterKind} to ask the user to approve a workspace action.",
    group: "approvals",
  },
  "userlandApproval.requestExternal": {
    title: "Ask the user to approve an external action",
    action: "ask the user to approve an external action",
    description: "Allows {requesterKind} to ask the user to approve an external action.",
    group: "approvals",
  },
  "userlandApproval.requestSecretInput": {
    title: "Ask the user for a protected value",
    action: "ask the user for a protected value",
    description: "Allows {requesterKind} to ask the user for a protected value.",
    group: "approvals",
  },
  "userlandApproval.requestSecretInputAs": {
    title: "Ask the user for a protected value",
    action: "ask the user for a protected value",
    description: "Allows {requesterKind} to ask the user for a protected value.",
    group: "approvals",
  },
  "userlandApproval.revoke": {
    title: "Remove a saved workspace-service decision",
    action: "remove a saved workspace-service decision",
    description: "Allows {requesterKind} to remove a saved workspace-service decision.",
    group: "approvals",
  },
  "userlandApproval.settleExternal": {
    title: "Record the result of an external action",
    action: "record the result of an external action",
    description: "Allows {requesterKind} to record the result of an external action.",
    group: "approvals",
  },
  "webhookIngress.createSubscription": {
    title: "Accept incoming web requests",
    action: "accept incoming web requests",
    description: "Allows {requesterKind} to accept incoming web requests.",
    group: "network",
  },
  "webhookIngress.listSubscriptions": {
    title: "View incoming web connections",
    action: "view incoming web connections",
    description: "Allows {requesterKind} to view incoming web connections.",
    group: "network",
  },
  "webhookIngress.revokeSubscription": {
    title: "Stop accepting an incoming web connection",
    action: "stop accepting an incoming web connection",
    description: "Allows {requesterKind} to stop accepting an incoming web connection.",
    group: "network",
  },
  "webhookIngress.rotateSecret": {
    title: "Replace an incoming web connection's secret",
    action: "replace an incoming web connection's secret",
    description: "Allows {requesterKind} to replace an incoming web connection's secret.",
    group: "network",
  },
  "workspace.ensureContextFolder": {
    title: "Prepare a task workspace folder",
    action: "prepare a task workspace folder",
    description: "Allows {requesterKind} to prepare a task workspace folder.",
    group: "workspace",
  },
  "workspace.heartbeats.pause": {
    title: "Pause recurring workspace tasks",
    action: "pause recurring workspace tasks",
    description: "Allows {requesterKind} to pause recurring workspace tasks.",
    group: "workspace",
  },
  "workspace.heartbeats.resume": {
    title: "Resume recurring workspace tasks",
    action: "resume recurring workspace tasks",
    description: "Allows {requesterKind} to resume recurring workspace tasks.",
    group: "workspace",
  },
  "workspace.heartbeats.runNow": {
    title: "Run recurring workspace tasks now",
    action: "run recurring workspace tasks now",
    description: "Allows {requesterKind} to run recurring workspace tasks now.",
    group: "workspace",
  },
  "workspace.hostTargets.beginLaunch": {
    title: "Start launching a workspace app",
    action: "start launching a workspace app",
    description: "Allows {requesterKind} to start launching a workspace app.",
    group: "workspace",
  },
  "workspace.hostTargets.cancelLaunchSession": {
    title: "Cancel an app launch",
    action: "cancel an app launch",
    description: "Allows {requesterKind} to cancel an app launch.",
    group: "workspace",
  },
  "workspace.hostTargets.clearSelection": {
    title: "Clear the selected app host",
    action: "clear the selected app host",
    description: "Allows {requesterKind} to clear the selected app host.",
    group: "workspace",
  },
  "workspace.hostTargets.getLaunchSession": {
    title: "View app launch progress",
    action: "view app launch progress",
    description: "Allows {requesterKind} to view app launch progress.",
    group: "workspace",
  },
  "workspace.hostTargets.getSelection": {
    title: "View the selected app host",
    action: "view the selected app host",
    description: "Allows {requesterKind} to view the selected app host.",
    group: "workspace",
  },
  "workspace.hostTargets.launch": {
    title: "Launch a workspace app",
    action: "launch a workspace app",
    description: "Allows {requesterKind} to launch a workspace app.",
    group: "workspace",
  },
  "workspace.hostTargets.list": {
    title: "View available app hosts",
    action: "view available app hosts",
    description: "Allows {requesterKind} to view available app hosts.",
    group: "workspace",
  },
  "workspace.hostTargets.preparePinnedRef": {
    title: "Prepare a fixed app version",
    action: "prepare a fixed app version",
    description: "Allows {requesterKind} to prepare a fixed app version.",
    group: "workspace",
  },
  "workspace.hostTargets.resolveLaunchSessionApproval": {
    title: "Respond to an app launch request",
    action: "respond to an app launch request",
    description: "Allows {requesterKind} to respond to an app launch request.",
    group: "workspace",
  },
  "workspace.hostTargets.setSelection": {
    title: "Select an app host",
    action: "select an app host",
    description: "Allows {requesterKind} to select an app host.",
    group: "workspace",
  },
  "workspace.hostTargets.versions": {
    title: "View available app versions",
    action: "view available app versions",
    description: "Allows {requesterKind} to view available app versions.",
    group: "workspace",
  },
  "workspace.setConfigField": {
    title: "Change workspace settings",
    action: "change workspace settings",
    description: "Allows {requesterKind} to change workspace settings.",
    group: "workspace",
  },
  "workspace.setInitPanels": {
    title: "Change startup panels",
    action: "change startup panels",
    description: "Allows {requesterKind} to change startup panels.",
    group: "workspace",
  },
  "workspace.units.bakeAppDist": {
    title: "Prepare app files for release",
    action: "prepare app files for release",
    description: "Allows {requesterKind} to prepare app files for release.",
    group: "workspace",
  },
  "workspace.units.restart": {
    title: "Restart a workspace app, panel, worker, or extension",
    action: "restart a workspace app, panel, worker, or extension",
    description: "Allows {requesterKind} to restart a workspace app, panel, worker, or extension.",
    group: "workspace",
  },
  "workspace.units.rollback": {
    title: "Restore a previous app, panel, worker, or extension version",
    action: "restore a previous app, panel, worker, or extension version",
    description:
      "Allows {requesterKind} to restore a previous app, panel, worker, or extension version.",
    group: "workspace",
  },
  "workspace-state.heartbeatRegister": {
    title: "Schedule a recurring workspace task",
    action: "schedule a recurring workspace task",
    description: "Allows {requesterKind} to schedule a recurring workspace task.",
    group: "panels",
  },
  "workspace-state.heartbeatRemove": {
    title: "Remove a recurring workspace task",
    action: "remove a recurring workspace task",
    description: "Allows {requesterKind} to remove a recurring workspace task.",
    group: "panels",
  },
  "workspace-state.panel.incrementAccess": {
    title: "Record panel use",
    action: "record panel use",
    description: "Allows {requesterKind} to record panel use.",
    group: "panels",
  },
  "workspace-state.panel.index": {
    title: "Update the panel index",
    action: "update the panel index",
    description: "Allows {requesterKind} to update the panel index.",
    group: "panels",
  },
  "workspace-state.panel.rebuildIndex": {
    title: "Rebuild the panel index",
    action: "rebuild the panel index",
    description: "Allows {requesterKind} to rebuild the panel index.",
    group: "panels",
  },
  "workspace-state.panel.updateTitle": {
    title: "Change a panel title",
    action: "change a panel title",
    description: "Allows {requesterKind} to change a panel title.",
    group: "panels",
  },
  "workspace-state.slot.close": {
    title: "Close a panel",
    action: "close a panel",
    description: "Allows {requesterKind} to close a panel.",
    group: "panels",
  },
  "workspace-state.slot.commitPreparedNavigation": {
    title: "Finish navigating a panel",
    action: "finish navigating a panel",
    description: "Allows {requesterKind} to finish navigating a panel.",
    group: "panels",
  },
  "workspace-state.slot.create": {
    title: "Create a panel slot",
    action: "create a panel slot",
    description: "Allows {requesterKind} to create a panel slot.",
    group: "panels",
  },
  "workspace-state.slot.move": {
    title: "Move a panel",
    action: "move a panel",
    description: "Allows {requesterKind} to move a panel.",
    group: "panels",
  },
  "workspace-state.slot.setParent": {
    title: "Change a panel's parent",
    action: "change a panel's parent",
    description: "Allows {requesterKind} to change a panel's parent.",
    group: "panels",
  },
  "workspace-state.slot.setPosition": {
    title: "Change a panel's position",
    action: "change a panel's position",
    description: "Allows {requesterKind} to change a panel's position.",
    group: "panels",
  },
  "workspace-state.slot.updateCurrentStateArgs": {
    title: "Change a panel's saved state",
    action: "change a panel's saved state",
    description: "Allows {requesterKind} to change a panel's saved state.",
    group: "panels",
  },
} as const satisfies Record<PromptableHostMethod, CapabilityPresentation>;

const effect = (
  title: string,
  group: string,
  action = `${title[0]!.toLowerCase()}${title.slice(1)}`
): CapabilityPresentation => ({
  title,
  action,
  description: `Allows {requesterKind} to ${action}.`,
  group,
});

/** Reviewed copy for the stable, manifest-facing effects shared by host methods. */
export const HOST_SEMANTIC_CAPABILITY_PRESENTATIONS = {
  "account-providers.configure": effect("Set up account providers", "credentials"),
  "account-providers.delete": effect("Delete account-provider settings", "credentials"),
  "account.profile.read": effect("View your account profile", "accounts"),
  "account.profile.update": effect("Change your account profile", "accounts"),
  "accounts.connect": effect("Connect accounts", "credentials"),
  "accounts.disconnect": effect("Disconnect accounts", "credentials"),
  "adblock.manage": effect("Manage ad blocking", "network"),
  "agent.credentials.manage": effect("Manage agent sign-in keys", "accounts"),
  "application.shutdown": effect("Close Vibestudio", "host"),
  "application.update": effect("Install Vibestudio updates", "host"),
  "approvals.block": effect("Block future access requests", "approvals"),
  "approvals.decide": effect("Respond to access requests", "approvals"),
  "approvals.read": effect("View requests awaiting your decision", "approvals"),
  "browser-passwords.delete": effect("Delete saved passwords", "credentials"),
  "browser-passwords.manage": effect("Change password-saving preferences", "credentials"),
  "browser-passwords.read": effect("View saved password accounts and preferences", "credentials"),
  "automations.control": effect("Run and pause workspace automations", "workspace"),
  "automations.register": effect("Schedule workspace automations", "workspace"),
  "code-runner.reset": effect("Reset the code runner", "runtime"),
  "connections.approve": effect("Approve new client connections", "accounts"),
  "content.trust.policy.manage": effect("Manage rules for trusting outside content", "approvals"),
  "content.trust.vouch": effect("Trust exact outside content", "approvals"),
  "context.clone": effect("Copy another task's working context", "runtime"),
  "context.materialize": effect("Create a task workspace folder", "files"),
  "context.relationships.record": effect("Record relationships between tasks", "runtime"),
  "credential.use": effect("Use connected accounts", "credentials"),
  "credentials.audit.read": effect("View connected-account activity", "credentials"),
  "devices.pair": effect("Pair a device", "accounts"),
  "devices.read": effect("View paired devices", "accounts"),
  "devices.revoke": effect("Remove paired devices", "accounts"),
  "extensions.diagnose": effect("Diagnose workspace extensions", "workspace"),
  "extensions.reload": effect("Reload workspace extensions", "workspace"),
  "external.open": effect("Open links in other applications", "network"),
  "git.project.import": effect("Import Git projects", "files"),
  "git.publish": effect("Publish workspace changes", "files"),
  "git.pull": effect("Bring in remote workspace changes", "files"),
  "git.remotes.manage": effect("Manage workspace publishing destinations", "files"),
  "governance.read": effect("View workspace governance rules", "approvals"),
  "mobile.devices.read": effect("View available mobile devices", "accounts"),
  "mobile.install": effect("Install an app on a mobile device", "host"),
  "mobile.pair": effect("Pair a mobile device", "accounts"),
  "missions.approve": effect("Approve agent automation plans", "approvals"),
  "missions.edit": effect("Create and edit agent automation plans", "runtime"),
  "missions.pause": effect("Pause and resume agent automations", "runtime"),
  "missions.retire": effect("Retire agent automations", "runtime"),
  "missions.run": effect("Start and finish agent automations", "runtime"),
  "network.response.read": effect("Let workspace apps read website responses", "network"),
  "panel.inspect": effect("Inspect and automate panels", "panels"),
  "panel.presence.read": effect("See who is using a panel", "panels"),
  "panel.presence.update": effect("Share which panels are in use", "panels"),
  "permissions.read": effect("View saved access decisions", "approvals"),
  "permissions.revoke": effect("Revoke saved access decisions", "approvals"),
  "presence.read": effect("View who is currently online", "accounts"),
  "protected-input.submit": effect("Submit protected account details", "credentials"),
  "push.manage": effect("Manage notification delivery", "notifications"),
  "push.send": effect("Send notifications", "notifications"),
  "remote-client.clear": effect("Disconnect the remote client", "accounts"),
  "remote-client.connect": effect("Connect the remote client", "accounts"),
  "remote-client.read": effect("View the connected remote client", "accounts"),
  "runtime.inspect": effect("Inspect workspace runtimes", "runtime"),
  "security.audit.read": effect("View the security activity log", "approvals"),
  "server-logs.read": effect("View workspace server logs", "runtime"),
  "settings.read": effect("View workspace settings", "workspace"),
  "subagents.create": effect("Create helper agents", "runtime"),
  "user-approval.request": effect("Ask you to approve an action", "approvals"),
  "user-approval.revoke": effect("Cancel pending access requests", "approvals"),
  "users.revoke": effect("Remove workspace users", "accounts"),
  "webhooks.manage": effect("Manage incoming web connections", "network"),
  "workspace-host.manage": effect("Open and manage workspace apps", "workspace"),
  "workspace-panels.manage": effect("Open and arrange workspace panels", "panels"),
  "workspace.build-cache.manage": effect(
    "Rebuild and clean workspace apps, panels, workers, and extensions",
    "workspace"
  ),
  "workspace.configure": effect("Change workspace settings", "workspace"),
  "workspace.dependencies.inspect": effect("View installed workspace packages", "workspace"),
  "workspace.dependencies.install": effect("Install workspace packages", "workspace"),
  "workspace.gateway.access": effect("Access addresses provided by this workspace", "network"),
  "workspace.members.manage": effect("Manage workspace members", "accounts"),
  "workspace.members.read": effect("View workspace members", "accounts"),
  "workspace.members.remove": effect("Remove workspace members", "accounts"),
  "workspace.storage.delete": effect("Delete stored workspace data", "files"),
  "workspace.storage.materialize": effect("Restore stored workspace files", "files"),
  "workspace-units.manage": effect(
    "Restart or roll back workspace apps, panels, workers, and extensions",
    "workspace"
  ),
  "workspace-units.publish": effect("Publish built workspace apps", "workspace"),
  "workspaces.create": effect("Create workspaces", "workspace"),
  "workspaces.delete": effect("Delete workspaces", "workspace"),
  "workspaces.open": effect("Open workspaces", "workspace"),
  "workspaces.read": effect("View available workspaces", "workspace"),
} as const satisfies Record<HostSemanticCapability, CapabilityPresentation>;

export function hostCapabilityPresentation(capability: string): CapabilityPresentation | null {
  if (Object.prototype.hasOwnProperty.call(HOST_SEMANTIC_CAPABILITY_PRESENTATIONS, capability)) {
    return HOST_SEMANTIC_CAPABILITY_PRESENTATIONS[
      capability as keyof typeof HOST_SEMANTIC_CAPABILITY_PRESENTATIONS
    ];
  }
  if (!capability.startsWith("service:")) return null;
  const method = capability.slice("service:".length);
  return Object.prototype.hasOwnProperty.call(HOST_CAPABILITY_PRESENTATIONS, method)
    ? HOST_CAPABILITY_PRESENTATIONS[method as keyof typeof HOST_CAPABILITY_PRESENTATIONS]
    : null;
}
